baseurl = "www.ditannan.me"
title = "以梦为马，不负韶华"
theme = "ghostwriter"
languageCode = "zh-Hans"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"
relativeURLs = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true
uglyURLs = true
footnotereturnlinkcontents = "↩"

[Author]
    name = "低碳南"
    profile = "https://www.facebook.com/zhimeng.xu.967"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "低碳南"
    description = "For you and future me"
    github = "https://github.com/ditannan"
    #gitlab = "https://gitlab.com/XXX"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/xu_zhimeng"
    stackoverflow = "https://stackoverflow.com/users/8794908/zhimeng-xu"
    email = "xzm9210@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "2006/01/02"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    footer = "&copy; [Zhimeng Xu](ditannan.me) 1992 -- 2018 | [Github](https://github.com/ditannan) | [Twitter](https://twitter.com/xu_zhimeng)"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1

[[menu.main]]
    name = "学习中"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "杂记"
    url = "/something/"
    weight = 3

[[menu.main]]
    name = "关于"
    url = "/page/about/"
    weight = 4
